[sources]
hotnews = "https://feeds.feedburner.com/hotnews/yvoq"

[filter.usr]
in = [ "hotnews" ]
contains = "USR"

[filter.barna]
in = [ "hotnews" ]
contains = "Barna"

[output]
combine = ["usr", "barna"]
