[sources]
hotnews = "https://feeds.feedburner.com/hotnews/yvoq"
orf_at = "https://rss.orf.at/news.xml"

[filter.usr]
in = [ "hotnews", "orf_at" ]
contains = "USR"

[filter.barna]
in = [ "usr" ]
contains = "Barna"

[output]
combine = ["barna"]

# expected:
# ["barna"]
# ["barna"], ["usr"]
# ["barna". "usr"], ["hotnews"]
# =======
